# Demo Pipeline for deployment of application mentioned in Manifests to Azure AKS Service

trigger:
- master

variables:
  vmImageName: 'ubuntu-latest'

stages:
- stage: Deploy
  displayName: Deploy stage

  jobs:
  - deployment: Deploy
    displayName: Deploy to AKS
    pool:
      vmImage: $(vmImageName)
    environment: 'development'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: '4447f88d-53cd-4199-9738-8783cc7740a3'
              definition: '1'
              buildVersionToDownload: 'latest'
              targetPath: '$(Pipeline.Workspace)'

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              kubernetesServiceConnection: 'Development-demo-aks-cluster-demo-namespace-1589649066347'
              namespace: 'development'
              manifests: '$(Pipeline.Workspace)/AzureSampleProjects/azure-vote.yaml'
